name: Local Android Build

on: [workflow_dispatch]

jobs:
  publish:
    name: Install and build for android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      #- uses: expo/expo-github-action@v5
      #  with:
      #    expo-version: 3.x
      #    expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
      #    expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - uses: actions/cache@v2
        id: turtle-cache
        with:
          path: ~/.turtle
          key: ${{ runner.os }}-turtle
      - name: Build
        run: |
          npm install -g turtle-cli
          turtle --version
          export PATH=$(yarn bin):$PATH
          yarn
          turtle setup:android
          echo $EXPO_ANDROID_KEYSTORE_BASE64 > expo-project.jks.base64
          base64 --decode expo-project.jks.base64 > expo-project.jks
          yarn turtle build:android --keystore-path ./expo-project.jks --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS --type apk -o chastilock.apk
        env:
          EXPO_ANDROID_KEYSTORE_BASE64: ${{ secrets.EXPO_ANDROID_KEYSTORE_BASE64 }}
          EXPO_ANDROID_KEYSTORE_ALIAS: ${{ secrets.EXPO_ANDROID_KEYSTORE_ALIAS }}
          EXPO_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
      - uses: actions/upload-artifact@v2
        with:
          name: chastilock.apk
          path: ./chastilock.apk